export const APP_NAME = "EdCona";

export const translations: Record<string, Record<string, string>> = {
  en: {
    'app_name': 'EdCona',
    'login_welcome': 'Welcome to EdCona',
    'login_subtitle': 'Connecting parents and teachers seamlessly.',
    'user_code': 'Your Code',
    'user_code_placeholder': 'Enter your login code',
    'login': 'Login',
    'logout': 'Logout',
    'dashboard': 'Dashboard',
    'students': 'Students',
    'marks': 'Marks',
    'homework': 'Homework',
    'attendance': 'Attendance',
    'announcements': 'Announcements',
    'leaderboard': 'Leaderboard',
    'settings': 'Settings',
    'select_language': 'Select Language',
    'select_student': 'Select a Student',
    'parent_of': 'Parent of',
    'teacher_of': 'Teacher',
    'top_5_things': 'Top 5 Things to Know',
    'ai_summary_loading': 'Generating AI summary...',
    'get_ai_summary': 'Get AI Summary',
    'strengths': 'Strengths',
    'weaknesses': 'Areas for Improvement',
    'recent_marks': 'All Grades',
    'view_all': 'View All',
    'no_marks': 'No marks recorded yet.',
    'homework_status': 'Homework Status',
    'due_date': 'Due on',
    'submitted': 'Submitted',
    'not_submitted': 'Not Submitted',
    'no_homework': 'No active homework assignments.',
    'overall_attendance': 'Overall Attendance',
    'present': 'Present',
    'absent': 'Absent',
    'late': 'Late',
    'no_attendance': 'No attendance data available.',
    'high_priority': 'High Priority',
    'medium_priority': 'Medium Priority',
    'low_priority': 'Low Priority',
    'no_announcements': 'No new announcements.',
    'video_tutorials': 'Video Tutorials',
    'how_to_use_app': 'How to use the app',
    'watch_now': 'Watch Now',
    'leaderboard_title': 'Class Leaderboard',
    'rank': 'Rank',
    'student_name': 'Student Name',
    'average_marks': 'Average Marks',
    'select_class': 'Select Class',
    'manage_homework': 'Manage Homework',
    'submissions': 'Submissions',
    'post_announcement': 'Post Announcement',
    'take_attendance': 'Take Attendance',
    'today': "Today",
    'update_attendance': 'Update Attendance',
    'all_present': 'All Present',
    'save': 'Save',
    'title': 'Title',
    'description': 'Description',
    'subject': 'Subject',
    'priority': 'Priority',
    'content': 'Content',
    'modern_assyrian': 'Modern Assyrian',
    'kurdish_sorani': 'Kurdish (Sorani)',
    'kurdish_bahdini': 'Kurdish (Bahdini)',
    'english': 'English',
    'arabic': 'Arabic',
    'speak': 'Read aloud',
    'speech_not_supported': 'Text-to-speech is not supported in your browser.',
    'error_gemini': 'Could not get AI summary. Please try again later.',
    'homework_submission_title': 'Homework Submissions',
    'homework_submission_desc': 'Unselect students who did not complete the homework.',
    'select_all': 'Select All',
    'deselect_all': 'Deselect All',
    'profile_summary': "{name}'s Profile Summary",
    'voice_not_available': "A voice for the {language} language is not installed on your device.",
    'performance': 'Performance',
    'admin': 'Admin',
    'overview': 'Overview',
    'teachers': 'Teachers',
    'graded_assignments': 'Graded Assignments',
    'total_submissions': 'Homework Submissions',
    'grade_distribution': 'Grade Distribution',
    'recent_activity': 'Recent Activity',
    'search_students': 'Search Students...',
    'search_teachers': 'Search Teachers...',
    'parent': 'Parent',
    'class': 'Class',
    'classes': 'Classes',
    'activity_by_teacher': 'Activity by Teacher',
    'homework_assigned': 'Homework Assigned',
    'total_students': 'Total Students',
    'total_teachers': 'Total Teachers',
    'posted_homework': 'posted homework',
    'posted_announcement': 'posted an announcement',
    'view_stats_for': 'View stats for',
    'user_codes': 'User Codes',
    'filter_by_role': 'Filter by Role',
    'all_roles': 'All Roles',
    'parents': 'Parents',
    'name': 'Name',
    'role': 'Role',
    'code': 'Code',
    'actions': 'Actions',
    'copy': 'Copy',
    'loading': 'Loading...',
    'student_codes': 'Student Codes',
    'student_codes_description': 'View and copy your children\'s login codes',
    'student': 'Student',
    'login_code': 'Login Code',
    'school_wide': 'School-wide Overview',
    'manage_grades': 'Manage Grades',
    'create_new_assignment': 'Create New Assignment',
    'edit_grades': 'Edit Grades',
    'assignment_title': 'Assignment Title',
    'max_marks': 'Max Marks',
    'no_assignments_yet': 'No assignments created for this class yet.',
    'save_grades': 'Save Grades',
    'assignment_details': 'Assignment Details',
    'management': 'Management',
    'add_class': 'Add Class',
    'class_name': 'Class Name',
    'add_student': 'Add Student',
    'student_name_label': 'Student Name',
    'link_to_parent': 'Link to Parent',
    'add_teacher': 'Add Teacher',
    'teacher_name_label': 'Teacher Name',
    'assign_to_classes': 'Assign to Classes',
    'add_subject': 'Add Subject',
    'subject_name': 'Subject Name',
    'assign_new_homework': 'Assign New Homework',
    'due_date_label': 'Due Date',
    'add_parent': 'Add Parent',
    'parent_name': 'Parent Name',
    'class_added': 'Class added successfully!',
    'student_added': 'Student added successfully!',
    'subject_added': 'Subject added successfully!',
    'homework_assigned_success': 'Homework assigned successfully!',
    'announcement_posted_success': 'Announcement posted successfully!',
    'grades_saved_success': 'Grades saved successfully!',
    'attendance_saved_success': 'Attendance saved successfully!',
    'submissions_saved_success': 'Submissions saved successfully!',
    'messages': 'Messages',
    'send_message': 'Send Message',
    'type_a_message': 'Type a message...',
    'conversation_with': 'Conversation with {name}',
    'no_messages_yet': 'No messages yet. Start the conversation!',
    'message_sent_success': 'Message sent successfully!',
    'parent_added_with_code': 'Parent added! Login Code: {code}',
    'teacher_added_with_code': 'Teacher added! Login Code: {code}',
    'student_added_with_code': 'Student added! Login code: {code}',
    'choose_your_character': 'Choose Your Character',
    'hello_student': 'Hello, {name}!',
    'character_selected': 'Character Selected!',
    'timetable': 'Timetable',
    'profile': 'Profile',
    'change_photo': 'Change Photo',
    'photo_updated_success': 'Photo updated successfully!',
    'delete': 'Delete',
    'confirm_delete_title': 'Confirm Deletion',
    'confirm_delete_homework_message': 'Are you sure you want to delete this homework assignment? This action cannot be undone.',
    'confirm_delete_assignment_message': 'Are you sure you want to delete this assignment and all its associated grades? This action cannot be undone.',
    'cancel': 'Cancel',
    'homework_deleted_success': 'Homework deleted successfully!',
    'assignment_deleted_success': 'Assignment deleted successfully!',
    'mark_all_present': 'Mark All Present',
    'availability': 'Availability',
    'available_from': 'Available From',
    'available_to': 'To',
    'save_availability': 'Save Availability',
    'availability_saved_success': 'Availability saved successfully!',
    'start_recording': 'Start Recording',
    'stop_recording': 'Stop Recording',
    'send_voice_message': 'Send Voice Message',
    'teacher_available': 'Available: {startTime} - {endTime}',
    'confirm_delete_student': 'Are you sure you want to delete this student?',
    'confirm_delete_teacher': 'Are you sure you want to delete this teacher?',
    'confirm_delete_user': 'Are you sure you want to delete {name}?',
    'no_grades_yet': 'No grades recorded yet',
    'no_teachers_yet': 'No teachers registered yet',
    'grades_assigned': 'grades assigned',
    'select_parent': 'Select Parent',
    'no_parents_available': 'No parents available. Please add a parent first.',
  },
  'ku-sorani': {
    'app_name': 'ئیدکۆنا',
    'login_welcome': 'بەخێربێن بۆ ئیدکۆنا',
    'login_subtitle': 'پەیوەندی بێ کێشەی نێوان دایبابان و مامۆستایان.',
    'user_code': 'کۆدی ئێوە',
    'user_code_placeholder': 'کۆدی چوونەژوورەوەت بنووسە',
    'login': 'چوونەژوورەوە',
    'logout': 'چوونەدەرەوە',
    'dashboard': 'سەرەکی',
    'students': 'قوتابیان',
    'marks': 'نمرەکان',
    'homework': 'کاری ماڵەوە',
    'attendance': 'ئامادەبوون',
    'announcements': 'ڕاگەیاندنەکان',
    'leaderboard': 'لیستی پێشەنگان',
    'settings': 'ڕێکخستنەکان',
    'select_language': 'زمان هەڵبژێرە',
    'select_student': 'قوتابیەک هەڵبژێرە',
    'parent_of': 'دایبابی',
    'teacher_of': 'مامۆستای',
    'top_5_things': '٥ گرنگترین شت کە پێویستە بیزانیت',
    'ai_summary_loading': 'کورتکراوەی زیرەک دروست دەکرێت...',
    'get_ai_summary': 'کورتکراوەی زیرەک وەربگرە',
    'strengths': 'خاڵە بەهێزەکان',
    'weaknesses': 'بوارەکانی پێویست بە باشترکردن',
    'recent_marks': 'هەموو نمرەکان',
    'view_all': 'هەمووی ببینە',
    'no_marks': 'هێشتا هیچ nmerەyەک تۆمار نەکراوە.',
    'homework_status': 'دۆخی کاری ماڵەوە',
    'due_date': 'تا ڕۆژی',
    'submitted': 'تەسلیم کراوە',
    'not_submitted': 'تەسلیم نەکراوە',
    'no_homework': 'هیچ ئەرکێکی ماڵەوەی چالاک نییە.',
    'overall_attendance': 'کۆی گشتی ئامادەبوون',
    'present': 'ئامادە',
    'absent': 'نائامادە',
    'late': 'دواکەوتوو',
    'no_attendance': 'هیچ داتایەکی ئامادەبوون بەردەست نییە.',
    'high_priority': 'گرنگی زۆر',
    'medium_priority': 'گرنگی مامناوەند',
    'low_priority': 'گرنگی کەم',
    'no_announcements': 'هیچ ڕاگەیاندنێکی نوێ نییە.',
    'video_tutorials': 'فێرکاری ڤیدیۆیی',
    'how_to_use_app': 'چۆنیەتی بەکارهێنانی ئەپەکە',
    'watch_now': 'ئێستا سەیر بکە',
    'leaderboard_title': 'لیستی پێشەنگانی پۆل',
    'rank': 'پلە',
    'student_name': 'ناوی قوتابی',
    'average_marks': 'تێکڕای نمرەکان',
    'select_class': 'پۆل هەڵبژێرە',
    'manage_homework': 'بەڕێوەبردنی کاری ماڵەوە',
    'submissions': 'تەسلیمکراوەکان',
    'post_announcement': 'ڕاگەیاندن بڵاو بکەرەوە',
    'take_attendance': 'ئامادەبوون وەربگرە',
    'today': "ئەمڕۆ",
    'update_attendance': 'نوێکردنەوەی ئامادەبوون',
    'all_present': 'هەموو ئامادەن',
    'save': 'پاشەکەوت',
    'title': 'ناونیشان',
    'description': 'شیکردنەوە',
    'subject': 'بابەت',
    'priority': 'گرنگی',
    'content': 'ناوەڕۆک',
    'modern_assyrian': 'ئاشووری نوێ',
    'kurdish_sorani': 'کوردی (سۆرانی)',
    'kurdish_bahdini': 'کوردی (بادینی)',
    'english': 'ئینگلیزی',
    'arabic': 'عەرەبی',
    'speak': 'بە دەنگ بیخوێنەرەوە',
    'speech_not_supported': 'خوێندنەوەی دەق بە دەنگ لە وێبگەڕەکەتدا پشتگیری ناکرێت.',
    'error_gemini': 'نەتوانرا کورتکراوەی زیرەک وەربگیرێت. تکایە دواتر هەوڵ بدەرەوە.',
    'homework_submission_title': 'تەسلیمکردنی ئەرکی ماڵەوە',
    'homework_submission_desc': 'ئەو قوتابیانە هەڵمەبژێرە کە ئەرکی ماڵەوەیان تەواو نەکردووە.',
    'select_all': 'هەمووی هەڵبژێرە',
    'deselect_all': 'هەڵوەشاندنەوەی هەموو',
    'profile_summary': "کورتەی پرۆفایلی {name}",
    'voice_not_available': "دەنگێک بۆ زمانی {language} لەسەر ئامێرەکەت دامەزراو نییە.",
    'performance': 'ئەنجام',
    'admin': 'بەرێوەبەر',
    'overview': 'گشتی',
    'teachers': 'مامۆستایان',
    'graded_assignments': 'ئەرکە نمرەکراوەکان',
    'total_submissions': 'کۆی تەسلیمکراوەکان',
    'grade_distribution': 'دابەشبوونی نمرەکان',
    'recent_activity': 'چالاکی دوایی',
    'search_students': 'گەڕان بۆ قوتابیان...',
    'search_teachers': 'گەڕان بۆ مامۆستایان...',
    'parent': 'دایباب',
    'class': 'پۆل',
    'classes': 'پۆلەکان',
    'activity_by_teacher': 'چالاکی بەپێی مامۆستا',
    'homework_assigned': 'کاری ماڵەوەی سپێردراو',
    'total_students': 'کۆی قوتابیان',
    'total_teachers': 'کۆی مامۆستایان',
    'posted_homework': 'کاری ماڵەوەی بڵاوکردەوە',
    'posted_announcement': 'ڕاگەیاندنێکی بڵاوکردەوە',
    'view_stats_for': 'بینینی ئامارەکان بۆ',
    'school_wide': 'گشتی قوتابخانە',
    'manage_grades': 'بەڕێوەبردنی نمرەکان',
    'create_new_assignment': 'دانانی ئەرکی نوێ',
    'edit_grades': 'دەستکاریکردنی نمرەکان',
    'assignment_title': 'ناونیشانی ئەرک',
    'max_marks': 'نمرەی ماکسیمم',
    'no_assignments_yet': 'هێشتا هیچ ئەرکێک بۆ ئەم پۆلە دروست نەکراوە.',
    'save_grades': 'پاشەکەوتکردنی نمرەکان',
    'assignment_details': 'وردەکارییەکانی ئەرک',
    'management': 'بەڕێوەبردن',
    'add_class': 'زیادکردنی پۆل',
    'class_name': 'ناوی پۆل',
    'add_student': 'زیادکردنی قوتابی',
    'student_name_label': 'ناوی قوتابی',
    'link_to_parent': 'بەستنەوە بە دایباب',
    'add_teacher': 'زیادکردنی مامۆستا',
    'teacher_name_label': 'ناوی مامۆستا',
    'assign_to_classes': 'دانان بۆ پۆلەکان',
    'add_subject': 'زیادکردنی بابەت',
    'subject_name': 'ناوی بابەت',
    'assign_new_homework': 'دانانی ئەرکی ماڵەوەی نوێ',
    'due_date_label': 'کاتی دیاریکراو',
    'add_parent': 'زیادکردنی دایباب',
    'parent_name': 'ناوی دایباب',
    'class_added': 'پۆل بە سەرکەوتوویی زیادکرا!',
    'student_added': 'قوتابی بە سەرکەوتوویی زیادکرا!',
    'subject_added': 'بابەت بە سەرکەوتوویی زیادکرا!',
    'homework_assigned_success': 'ئەرکی ماڵەوە بە سەرکەوتوویی سپێردرا!',
    'announcement_posted_success': 'ڕاگەیاندن بە سەرکەوتوویی بڵاوکرایەوە!',
    'grades_saved_success': 'نمرەکان بە سەرکەوتوویی پاشەکەوت کران!',
    'attendance_saved_success': 'ئامادەبوون بە سەرکەوتوویی پاشەکەوت کرا!',
    'submissions_saved_success': 'تەسلیمکراوەکان بە سەرکەوتوویی پاشەکەوت کران!',
    'messages': 'نامەکان',
    'send_message': 'نامە بنێرە',
    'type_a_message': 'نامەیەک بنووسە...',
    'conversation_with': 'گفتوگۆ لەگەڵ {name}',
    'no_messages_yet': 'هێشتا هیچ نامەیەک نییە. دەست بە گفتوگۆ بکە!',
    'message_sent_success': 'نامە بە سەرکەوتوویی نێردرا!',
    'parent_added_with_code': 'دایباب زیادکرا! کۆدی چوونەژوورەوە: {code}',
    'teacher_added_with_code': 'مامۆستا زیادکرا! کۆدی چوونەژوورەوە: {code}',
    'student_added_with_code': 'قوتابی زیادکرا! کۆدی چوونەژوورەوە: {code}',
    'choose_your_character': 'کەسایەتییەکەت هەڵبژێرە',
    'hello_student': 'سڵاو، {name}!',
    'character_selected': 'کەسایەتی هەڵبژێردرا!',
    'timetable': 'خشتەی کات',
    'profile': 'پرۆفایل',
    'change_photo': 'گۆڕینی وێنە',
    'photo_updated_success': 'وێنە بە سەرکەوتوویی نوێکرایەوە!',
    'delete': 'سڕینەوە',
    'confirm_delete_title': 'پشتڕاستکردنەوەی سڕینەوە',
    'confirm_delete_homework_message': 'دڵنیایت لە سڕینەوەی ئەم ئەرکەی ماڵەوە؟ ئەم کردارە ناتوانرێت بگەڕێندرێتەوە.',
    'confirm_delete_assignment_message': 'دڵنیایت لە سڕینەوەی ئەم ئەرکە و هەموو نمرە پەیوەندیدارەکانی؟ ئەم کردارە ناتوانرێت بگەڕێندرێتەوە.',
    'cancel': 'هەڵوەشاندنەوە',
    'homework_deleted_success': 'ئەرکی ماڵەوە بە سەرکەوتوویی سڕایەوە!',
    'assignment_deleted_success': 'ئەرک بە سەرکەوتوویی سڕایەوە!',
    'mark_all_present': 'هەموو ئامادە بکە',
    'availability': 'کاتەکانی بەردەستبوون',
    'available_from': 'بەردەستە لە',
    'available_to': 'بۆ',
    'save_availability': 'پاشەکەوتکردنی کات',
    'availability_saved_success': 'کاتەکانی بەردەستبوون پاشەکەوت کرا!',
    'start_recording': 'دەستپێکردنی تۆمارکردن',
    'stop_recording': 'وەستاندنی تۆمارکردن',
    'send_voice_message': 'ناردنی نامەی دەنگی',
    'teacher_available': 'بەردەستە: {startTime} - {endTime}',
    'user_codes': 'کۆدەکانی بەکارهێنەر',
    'filter_by_role': 'فلتەرکردن بەپێی ڕۆڵ',
    'all_roles': 'هەموو ڕۆڵەکان',
    'parents': 'دایبابەکان',
    'name': 'ناو',
    'role': 'ڕۆڵ',
    'code': 'کۆد',
    'actions': 'کردارەکان',
    'copy': 'کۆپی',
    'loading': 'چاوەڕوان...',
    'student_codes': 'کۆدەکانی قوتابی',
    'student_codes_description': 'بینین و کۆپیکردنی کۆدەکانی چوونەژوورەوەی منداڵەکانت',
    'student': 'قوتابی',
    'login_code': 'کۆدی چوونەژوورەوە',
    'confirm_delete_student': 'دڵنیایت کە دەتەوێت ئەم قوتابییە بسڕیتەوە؟',
    'confirm_delete_teacher': 'دڵنیایت کە دەتەوێت ئەم مامۆستایە بسڕیتەوە؟',
    'confirm_delete_user': 'دڵنیایت کە دەتەوێت {name} بسڕیتەوە؟',
    'no_grades_yet': 'هێشتا هیچ نمرە نەکراوە.',
    'no_teachers_yet': 'هێشتا هیچ مامۆستای نەکراوە.',
    'grades_assigned': 'نمرەکان بە سەرکەوتوویی پاشەکەوت کران.',
    'select_parent': 'دایبابی هەڵبژێرە',
    'no_parents_available': 'هیچ دایبابەکان نەبوو. لەوەی بەردەست بنووسە بە دایبابەکان.',
  },
  'ku-badini': {
    'app_name': 'ئیدکۆنا',
    'login_welcome': 'بخێرھاتن بۆ ئیدکۆنا',
    'login_subtitle': 'گرێدانا دەیباب و مامۆستایان ب سانەھی.',
    'user_code': 'کودێ تە',
    'user_code_placeholder': 'کودێ خوە یێ چوونا ژوور بنڤیسە',
    'login': 'چوونا ژوور',
    'logout': 'چوونا دەر',
    'dashboard': 'سەرەکی',
    'students': 'قوتابی',
    'marks': 'نمرە',
    'homework': 'کارێ مال',
    'attendance': 'ئامادەبوون',
    'announcements': 'ڕاگەھاندن',
    'leaderboard': 'لیستا پێشەنگان',
    'settings': 'ڕێکخستن',
    'select_language': 'زمانێ ھەلبژێرە',
    'select_student': 'قوتابیەکێ ھەلبژێرە',
    'parent_of': 'دەیبابێ',
    'teacher_of': 'مامۆستایێ',
    'top_5_things': '٥ تشتێن گرنگ کو دڤێت بزانی',
    'ai_summary_loading': 'کورتەیا زیرەک دھێتە دروستکرن...',
    'get_ai_summary': 'کورتەیا زیرەک وەرگرە',
    'strengths': 'خالێن بھێز',
    'weaknesses': 'جهێن پێدڤی ب باشترکرنێ',
    'recent_marks': 'ھەمی نمرە',
    'view_all': 'ھەمیێ ببینە',
    'no_marks': 'ھێشتا چ نمرە نەھاتینە تومارکرن.',
    'homework_status': 'رەوشا کارێ مال',
    'due_date': 'ھەتا رۆژا',
    'submitted': 'ھاتیە رادەستکرن',
    'not_submitted': 'نەھاتیە رادەستکرن',
    'no_homework': 'چ ئەرکێن مال یێن چالاک نینن.',
    'overall_attendance': 'کۆما گشتی یا ئامادەبوونێ',
    'present': 'ئامادە',
    'absent': 'نائامادە',
    'late': 'گیرۆبوویی',
    'no_attendance': 'چ داتایێن ئامادەبوونێ نینن.',
    'high_priority': 'گرنگیا زۆر',
    'medium_priority': 'گرنگیا ناڤنجی',
    'low_priority': 'گرنگیا کێم',
    'no_announcements': 'چ ڕاگەھاندنێن نوی نینن.',
    'video_tutorials': 'فێرکاریێن ڤیدیۆیی',
    'how_to_use_app': 'چەوانیا بکارئینانا ئەپلیکەیشنێ',
    'watch_now': 'نوکە تەماشە بکە',
    'leaderboard_title': 'لیستا پێشەنگێن پولێ',
    'rank': 'پلە',
    'student_name': 'ناڤێ قوتابی',
    'average_marks': 'ناڤنجیا نمران',
    'select_class': 'پولێ ھەلبژێرە',
    'manage_homework': 'برێڤەبرنا کارێ مال',
    'submissions': 'رادەستکری',
    'post_announcement': 'ڕاگەھاندنەکێ بەلاڤ بکە',
    'take_attendance': 'ئامادەبوونێ وەرگرە',
    'today': 'ئەڤرۆ',
    'update_attendance': 'نویکرنا ئامادەبوونێ',
    'all_present': 'ھەمی ئامادەنە',
    'save': 'پاراستن',
    'title': 'ناڤونیشان',
    'description': 'شلوڤەکرن',
    'subject': 'بابەت',
    'priority': 'گرنگی',
    'content': 'ناڤەرۆک',
    'modern_assyrian': 'ئاشووریێ نوی',
    'kurdish_sorani': 'کوردی (سۆرانی)',
    'kurdish_bahdini': 'کوردی (بادینی)',
    'english': 'ئینگلیزی',
    'arabic': 'عەرەبی',
    'speak': 'ب دەنگ بخوینە',
    'speech_not_supported': 'خواندنەوەیا دەقی ب دەنگ ل ناڤ ویبگەرێ تە دا ناهێتە پشتەڤانیکرن.',
    'error_gemini': 'کورتەیا زیرەک نەھاتە وەرگرتن. تکایە پاشتر ھەول بدە.',
    'homework_submission_title': 'رادەستکرنا ئەرکێن مال',
    'homework_submission_desc': 'وان قوتابیان ھەلبنژێرە یێن ئەرکێن خۆ یێن مال ئەنجام نەداین.',
    'select_all': 'ھەمی ھەلبژێرە',
    'deselect_all': 'ھەمیێ ھەلوەشینە',
    'profile_summary': "کورتەیا پرۆفایلێ {name}",
    'voice_not_available': "دەنگەک بۆ زمانێ {language} ل سەر ئامیرێ تە نەهاتیە دامەزراندن.",
    'performance': 'ئەنجام',
    'admin': 'رێڤەبەر',
    'overview': 'گشتی',
    'teachers': 'مامۆستا',
    'graded_assignments': 'ئەرکێن نمرەکری',
    'total_submissions': 'کۆما رادەستکریان',
    'grade_distribution': 'دابەشکرنا نمران',
    'recent_activity': 'چالاکیێن داویێ',
    'search_students': 'ل قوتابیان بگەڕێ...',
    'search_teachers': 'ل مامۆستایان بگەڕێ...',
    'parent': 'دەیباب',
    'class': 'پول',
    'classes': 'پول',
    'activity_by_teacher': 'چالاکی ب گۆرەی مامۆستای',
    'homework_assigned': 'کارێ مالێ یێ ھاتیە دان',
    'total_students': 'کۆما قوتابیان',
    'total_teachers': 'کۆما مامۆستایان',
    'posted_homework': 'کارێ مالێ بەلاڤکر',
    'posted_announcement': 'راگەھاندنەک بەلاڤکر',
    'view_stats_for': 'دیتنا ئاماران بۆ',
    'school_wide': 'گشتیا خواندنگهێ',
    'manage_grades': 'برێڤەبرنا نمران',
    'create_new_assignment': 'دانانا ئەرکەکا نوی',
    'edit_grades': 'دەستکاریکرنا نمران',
    'assignment_title': 'ناڤونیشانێ ئەرکێ',
    'max_marks': 'بلندترین نمرە',
    'no_assignments_yet': 'ھێشتا چ ئەرک بۆ ڤی پۆلی نەھاتینە دروستکرن.',
    'save_grades': 'نمران بپارێزە',
    'assignment_details': 'جزئیاتێن ئەرکێ',
    'management': 'برێڤەبرن',
    'add_class': 'پولەکا نوی زێدە بکە',
    'class_name': 'ناڤێ پولێ',
    'add_student': 'قوتابیەکێ نوی زێدە بکە',
    'student_name_label': 'ناڤێ قوتابی',
    'link_to_parent': 'ب دەیبابەکی ڤە گرێدە',
    'add_teacher': 'مامۆستایەکێ نوی زێدە بکە',
    'teacher_name_label': 'ناڤێ مامۆستای',
    'assign_to_classes': 'دانان بۆ پۆلەکان',
    'add_subject': 'بابەتەکێ نوی زێدە بکە',
    'subject_name': 'ناڤێ بابەتێ',
    'assign_new_homework': 'کارێ مالێ نوی دەینە',
    'due_date_label': 'رۆژا دوماھیێ',
    'add_parent': 'دەیبابەکێ نوی زێدە بکە',
    'parent_name': 'ناڤێ دەیباب',
    'class_added': 'پۆل ب سەرکەفتی ھاتە زێدەکرن!',
    'student_added': 'قوتابی ب سەرکەفتی ھاتە زێدەکرن!',
    'subject_added': 'بابەت ب سەرکەفتی ھاتە زێدەکرن!',
    'homework_assigned_success': 'کارێ مالێ ب سەرکەفتی ھاتە دان!',
    'announcement_posted_success': 'راگەھاندن ب سەرکەفتی ھاتە بەلاڤکرن!',
    'grades_saved_success': 'نمرە ب سەرکەفتی ھاتنە پاراستن!',
    'attendance_saved_success': 'ئامادەبوون ب سەرکەفتی ھاتە پاراستن!',
    'submissions_saved_success': 'رادەستکری ب سەرکەفتی ھاتنە پاراستن!',
    'messages': 'نامە',
    'send_message': 'نامەیەکێ فرێکە',
    'type_a_message': 'نامەیەکێ بنڤیسە...',
    'conversation_with': 'ئاخفتن دگەل {name}',
    'no_messages_yet': 'ھێشتا چ نامە نینن. دەست ب ئاخفتنێ بکە!',
    'message_sent_success': 'نامە ب سەرکەفتی ھاتە فرێکرن!',
    'parent_added_with_code': 'دەیباب زێدەبوو! کودێ چوونا ژوور: {code}',
    'teacher_added_with_code': 'مامۆستا زێدەبوو! کودێ چوونا ژوور: {code}',
    'student_added_with_code': 'قوتابی زێدەبوو! کودێ چوونا ژوور: {code}',
    'choose_your_character': 'کەسایەتیا خوە ھەلبژێرە',
    'hello_student': 'سلاڤ، {name}!',
    'character_selected': 'کەسایەتی ھاتە ھەلبژاردن!',
    'timetable': 'خشتەیا دەمان',
    'profile': 'پروفایل',
    'change_photo': 'وێنەی بگوهۆرە',
    'photo_updated_success': 'وێنە ب سەرکەفتی هاتە نویکرن!',
    'delete': 'ژێبرن',
    'confirm_delete_title': 'پشتراستکرنا ژێبرنێ',
    'confirm_delete_homework_message': 'تو پشتراستی دێ ڤی کارێ مالێ ژێبری؟ ئەڤ کردارە ناهێتە پاشڤەبرن.',
    'confirm_delete_assignment_message': 'تو پشتراستی دێ ڤی ئەرکی و هەمی نمرێن پەیوەندیدارەکانی؟ ئەم کردارە ناتوانرێت بگەڕێندرێتەوە.',
    'cancel': 'پاشگەزبوون',
    'homework_deleted_success': 'کارێ مالێ ب سەرکەفتی هاتە ژێبرن!',
    'assignment_deleted_success': 'ئەرک بە سەرکەفتی هاتە ژێبرن!',
    'mark_all_present': 'هەمی ئامادە بکە',
    'availability': 'دەما بەردەست',
    'available_from': 'بەردەست ژ',
    'available_to': 'بۆ',
    'save_availability': 'پاراستنا دەمی',
    'availability_saved_success': 'دەمێ بەردەست هاتە پاراستن!',
    'start_recording': 'دەستپێکرنا تۆمارکرنێ',
    'stop_recording': 'راوەستاندنا تۆمارکرنێ',
    'send_voice_message': 'فرێکرنا ناما دەنگی',
    'teacher_available': 'بەردەستە: {startTime} - {endTime}',
    'user_codes': 'کودێن بکارهێنەرێ',
    'filter_by_role': 'فلتەرکردن بەپێی ڕۆڵێ',
    'all_roles': 'هەمی ڕۆڵێن',
    'parents': 'دایبابێن',
    'name': 'ناڤ',
    'role': 'ڕۆڵ',
    'code': 'کۆد',
    'actions': 'کردارێن',
    'copy': 'کۆپی',
    'loading': 'چاوەڕوان...',
    'student_codes': 'کودێن قوتابیێن',
    'student_codes_description': 'دیتن و کۆپیکرنا کودێن چوونا ژوورێن منداڵێن تە',
    'student': 'قوتابی',
    'login_code': 'کودێ چوونا ژوورێ',
    'confirm_delete_student': 'تو پشتراستی دێ ڤی قوتابی ژێبری؟',
    'confirm_delete_teacher': 'تو پشتراستی دێ ڤی مامۆستای ژێبری؟',
    'confirm_delete_user': 'تو پشتراستی دێ {name} ژێبری؟',
    'no_grades_yet': 'هێشتا هیچ نمرە نەکراوە.',
    'no_teachers_yet': 'هێشتا هیچ مامۆستای نەکراوە.',
    'grades_assigned': 'نمرەکان بە سەرکەوتوویی پاشەکەوت کران.',
    'select_parent': 'دایبابی هەڵبژێرە',
    'no_parents_available': 'هیچ دایبابەکان نەبوو. لەوەی بەردەست بنووسە بە دایبابەکان.',
  },
  'ar': {
    'app_name': 'إدكونا',
    'login_welcome': 'مرحباً في إدكونا',
    'login_subtitle': 'ربط أولياء الأمور والمعلمين بسلاسة.',
    'user_code': 'الكود الخاص بك',
    'user_code_placeholder': 'أدخل رمز الدخول الخاص بك',
    'login': 'تسجيل الدخول',
    'logout': 'تسجيل الخروج',
    'dashboard': 'لوحة التحكم',
    'students': 'الطلاب',
    'marks': 'الدرجات',
    'homework': 'الواجبات المنزلية',
    'attendance': 'الحضورو',
    'announcements': 'الإعلانات',
    'leaderboard': 'لوحة الصدارة',
    'settings': 'الإعدادات',
    'select_language': 'اختر اللغة',
    'select_student': 'اختر طالبًا',
    'parent_of': 'ولي أمر',
    'teacher_of': 'معلم',
    'top_5_things': 'أهم 5 أشياء يجب معرفتها',
    'ai_summary_loading': 'جاري إنشاء ملخص الذكاء الاصطناعي...',
    'get_ai_summary': 'احصل على ملخص الذكاء الاصطناعي',
    'strengths': 'نقاط القوة',
    'weaknesses': 'مجالات التحسين',
    'recent_marks': 'كل الدرجات',
    'view_all': 'عرض الكل',
    'no_marks': 'لا توجد درجات مسجلة بعد.',
    'homework_status': 'حالة الواجبات المنزلية',
    'due_date': 'تاريخ الاستحقاق',
    'submitted': 'تم التسليم',
    'not_submitted': 'لم يتم التسليم',
    'no_homework': 'لا توجد واجبات منزلية نشطة.',
    'overall_attendance': 'الحاضرين',
    'present': 'حاضر',
    'absent': 'غائب',
    'late': 'متأخر',
    'no_attendance': 'لا توجد بيانات حضور متاحة.',
    'high_priority': 'أولوية عالية',
    'medium_priority': 'أولوية متوسطة',
    'low_priority': 'أولوية منخفضة',
    'no_announcements': 'لا توجد إعلانات جديدة.',
    'video_tutorials': 'شروحات الفيديو',
    'how_to_use_app': 'كيفية استخدام التطبيق',
    'watch_now': 'شاهد الآن',
    'leaderboard_title': 'لوحة صدارة الفصل',
    'rank': 'الترتيب',
    'student_name': 'اسم الطالب',
    'average_marks': 'متوسط الدرجات',
    'select_class': 'اختر الفصل',
    'manage_homework': 'إدارة الواجبات',
    'submissions': 'التسليمات',
    'post_announcement': 'نشر إعلان',
    'take_attendance': 'تسجيل الحضور',
    'today': 'اليوم',
    'update_attendance': 'تحديث الحضور',
    'all_present': 'الكل حاضر',
    'save': 'حفظ',
    'title': 'العنوان',
    'description': 'الوصف',
    'subject': 'المادة',
    'priority': 'الأولوية',
    'content': 'المحتوى',
    'modern_assyrian': 'الآشورية الحديثة',
    'kurdish_sorani': 'الكردية (السورانية)',
    'kurdish_bahdini': 'الكردية (البهدينية)',
    'english': 'الإنجليزية',
    'arabic': 'العربية',
    'speak': 'اقرأ بصوت عالٍ',
    'speech_not_supported': 'تحويل النص إلى كلام غير مدعوم في متصفحك.',
    'error_gemini': 'لا يمكن الحصول على ملخص الذكاء الاصطناعي. يرجى المحاولة مرة أخرى لاحقًا.',
    'homework_submission_title': 'تسليمات الواجبات',
    'homework_submission_desc': 'قم بإلغاء تحديد الطلاب الذين لم يكملوا الواجب.',
    'select_all': 'تحديد الكل',
    'deselect_all': 'إلغاء تحديد الكل',
    'profile_summary': "ملخص ملف {name}",
    'voice_not_available': "لا يوجد صوت مثبت للغة {language} على جهازك.",
    'performance': 'الأداء',
    'admin': 'المسؤول',
    'overview': 'نظرة عامة',
    'teachers': 'المعلمون',
    'graded_assignments': 'الواجبات المصححة',
    'total_submissions': 'إجمالي التسليمات',
    'grade_distribution': 'توزيع الدرجات',
    'recent_activity': 'النشاط الأخير',
    'search_students': 'ابحث عن الطلاب...',
    'search_teachers': 'ابحث عن المعلمين...',
    'parent': 'ولي الأمر',
    'class': 'الفصل',
    'classes': 'الفصول',
    'activity_by_teacher': 'نشاط حسب المعلم',
    'homework_assigned': 'الواجبات المعينة',
    'total_students': 'إجمالي الطلاب',
    'total_teachers': 'إجمالي المعلمين',
    'posted_homework': 'نشر واجبًا منزليًا',
    'posted_announcement': 'نشر إعلانًا',
    'view_stats_for': 'عرض الإحصائيات لـ',
    'school_wide': 'نظرة عامة على المدرسة',
    'manage_grades': 'إدارة الدرجات',
    'create_new_assignment': 'إنشاء واجب جديد',
    'edit_grades': 'تعديل الدرجات',
    'assignment_title': 'عنوان الواجب',
    'max_marks': 'الدرجة القصوى',
    'no_assignments_yet': 'لم يتم إنشاء واجبات لهذا الفصل بعد.',
    'save_grades': 'حفظ الدرجات',
    'assignment_details': 'تفاصيل الواجب',
    'management': 'إدارة',
    'add_class': 'إضافة فصل',
    'class_name': 'اسم الفصل',
    'add_student': 'إضافة طالب',
    'student_name_label': 'اسم الطالب',
    'link_to_parent': 'ربط بولي الأمر',
    'add_teacher': 'إضافة معلم',
    'teacher_name_label': 'اسم المعلم',
    'assign_to_classes': 'تعيين للفصول',
    'add_subject': 'إضافة مادة',
    'subject_name': 'اسم المادة',
    'assign_new_homework': 'تعيين واجب جديد',
    'due_date_label': 'تاريخ الاستحقاق',
    'add_parent': 'إضافة ولي أمر',
    'parent_name': 'اسم ولي الأمر',
    'class_added': 'تمت إضافة الفصل بنجاح!',
    'student_added': 'تمت إضافة الطالب بنجاح!',
    'subject_added': 'تمت إضافة المادة بنجاح!',
    'homework_assigned_success': 'تم تعيين الواجب بنجاح!',
    'announcement_posted_success': 'تم نشر الإعلان بنجاح!',
    'grades_saved_success': 'تم حفظ الدرجات بنجاح!',
    'attendance_saved_success': 'تم حفظ الحضور بنجاح!',
    'submissions_saved_success': 'تم حفظ التسليمات بنجاح!',
    'messages': 'الرسائل',
    'send_message': 'إرسال رسالة',
    'type_a_message': 'اكتب رسالة...',
    'conversation_with': 'محادثة مع {name}',
    'no_messages_yet': 'لا توجد رسائل بعد. ابدأ المحادثة!',
    'message_sent_success': 'تم إرسال الرسالة بنجاح!',
    'parent_added_with_code': 'تمت إضافة ولي الأمر! رمز الدخول: {code}',
    'teacher_added_with_code': 'تمت إضافة المعلم! رمز الدخول: {code}',
    'student_added_with_code': 'تمت إضافة الطالب! رمز الدخول: {code}',
    'choose_your_character': 'اختر شخصيتك',
    'hello_student': 'مرحباً، {name}!',
    'character_selected': 'تم اختيار الشخصية!',
    'timetable': 'الجدول الزمني',
    'profile': 'الملف الشخصي',
    'change_photo': 'تغيير الصورة',
    'photo_updated_success': 'تم تحديث الصورة بنجاح!',
    'delete': 'حذف',
    'confirm_delete_title': 'تأكيد الحذف',
    'confirm_delete_homework_message': 'هل أنت متأكد من أنك تريد حذف هذا الواجب المنزلي؟ لا يمكن التراجع عن هذا الإجراء.',
    'confirm_delete_assignment_message': 'هل أنت متأكد من أنك تريد حذف هذا الواجب وجميع الدرجات المرتبطة به؟ لا يمكن التراجع عن هذا الإجراء.',
    'cancel': 'إلغاء',
    'homework_deleted_success': 'تم حذف الواجب المنزلي بنجاح!',
    'assignment_deleted_success': 'تم حذف الواجب بنجاح!',
    'mark_all_present': 'تحديد الكل كحاضر',
    'availability': 'التوفر',
    'available_from': 'متاح من',
    'available_to': 'إلى',
    'save_availability': 'حفظ التوفر',
    'availability_saved_success': 'تم حفظ التوفر بنجاح!',
    'start_recording': 'بدء التسجيل',
    'stop_recording': 'إيقاف التسجيل',
    'send_voice_message': 'إرسال رسالة صوتية',
    'teacher_available': 'متاح: {startTime} - {endTime}',
    'user_codes': 'رموز المستخدمين',
    'filter_by_role': 'تصفية حسب الدور',
    'all_roles': 'جميع الأدوار',
    'parents': 'أولياء الأمور',
    'name': 'الاسم',
    'role': 'الدور',
    'code': 'الرمز',
    'actions': 'الإجراءات',
    'copy': 'نسخ',
    'loading': 'جاري التحميل...',
    'student_codes': 'رموز الطلاب',
    'student_codes_description': 'عرض ونسخ رموز تسجيل دخول أطفالك',
    'student': 'طالب',
    'login_code': 'رمز تسجيل الدخول',
    'confirm_delete_student': 'هل أنت متأكد من أنك تريد حذف هذا الطالب؟',
    'confirm_delete_teacher': 'هل أنت متأكد من أنك تريد حذف هذا المعلم؟',
    'confirm_delete_user': 'هل أنت متأكد أنك تريد حذف {name}؟',
    'no_grades_yet': 'لم يتم إنشاء درجات بعد.',
    'no_teachers_yet': 'لم يتم إنشاء معلمين بعد.',
    'grades_assigned': 'تم تعيين درجات بنجاح.',
    'select_parent': 'اختيار ولي الأمر',
    'no_parents_available': 'لا توجد أولياء أمور. يرجى إضافة ولي الأمر أولاً.',
  },
  'syr': {
    'app_name': 'ܐܕܩܘܢܐ',
    'login_welcome': 'ܒܫܝܢܐ ܘܒܤܒܪܐ ܛܒܐ ܠܐܕܩܘܢܐ',
    'login_subtitle': 'ܩܫܪܐ ܕܐܒ̈ܗܐ ܘܡܠܦܢ̈ܐ ܒܠܚܘܕ.',
    'user_code': 'ܩܘܕܐ ܕܐܢܬ',
    'user_code_placeholder': 'ܥܒܪ ܩܘܕܐ ܕܥܠܠܬܐ ܕܐܢܬ',
    'login': 'ܥܒܘܪ',
    'logout': 'ܦܠܘܛ',
    'dashboard': 'ܠܘܚܐ ܕܩܘܡܐ',
    'students': 'ܬܠܡܝ̈ܕܐ',
    'marks': 'ܛܟ̈ܣܐ',
    'homework': 'ܥܒܕܐ ܕܒܝܬܐ',
    'attendance': 'ܐܬܘܬܐ',
    'announcements': 'ܡܘܕܥܢܘܬܐ',
    'leaderboard': 'ܠܘܚܐ ܕܫܘܪܝܐ',
    'settings': 'ܣܝܡ̈ܐ',
    'select_language': 'ܓܒܝ ܠܫܢܐ',
    'select_student': 'ܓܒܝ ܬܠܡܝܕܐ',
    'parent_of': 'ܐܒܐ ܕ',
    'teacher_of': 'ܡܠܦܢܐ',
    'top_5_things': '5 ܡܢܕܪ̈ܢܘܬܐ ܪ̈ܫܝܬܐ ܠܡܕܥܐ',
    'ai_summary_loading': 'ܦܘܣܩܢܐ ܕܐܘܡܢܘܬܐ ܢܟܝܠܬܐ ܓܒܠ...',
    'get_ai_summary': 'ܩܒܠ ܦܘܣܩܢܐ ܕܐܘܡܢܘܬܐ ܢܟܝܠܬܐ',
    'strengths': 'ܚܝܠ̈ܐ',
    'weaknesses': 'ܐܬܪ̈ܘܬܐ ܠܫܘܦܐ',
    'recent_marks': 'ܟܠ ܛܟ̈ܣܐ',
    'view_all': 'ܚܙܝ ܟܠ',
    'no_marks': 'ܠܝܬ ܛܟ̈ܣܐ ܟܬܝܒ̈ܐ ܥܕܟܝܠ.',
    'homework_status': 'ܐܝܟܢܝܘܬܐ ܕܥܒܕܐ ܕܒܝܬܐ',
    'due_date': 'ܙܒܢܐ ܕܫܘܠܡܐ',
    'submitted': 'ܐܫܬܠܡ',
    'not_submitted': 'ܠܐ ܐܫܬܠܡ',
    'no_homework': 'ܠܝܬ ܥܒܕܐ ܕܒܝܬܐ ܓܒܝܐ.',
    'overall_attendance': 'ܐܬܘܬܐ ܓܘܢܝܬܐ',
    'present': 'ܐܝܬܘܗܝ',
    'absent': 'ܠܝܬܘܗܝ',
    'late': 'ܥܘܗܪܐ',
    'no_attendance': 'ܠܝܬ ܝܕ̈ܥܬܐ ܕܐܬܘܬܐ.',
    'high_priority': 'ܩܕܡܝܘܬܐ ܥܠܝܬܐ',
    'medium_priority': 'ܩܕܡܝܘܬܐ ܡܨܥܝܬܐ',
    'low_priority': 'ܩܕܡܝܘܬܐ ܬܚܬܝܬܐ',
    'no_announcements': 'ܠܝܬ ܡܘܕܥܢܘܬܐ ܚܕ̈ܬܐ.',
    'video_tutorials': 'ܬܘܪ̈ܓܡܐ ܕܒܝܕܝܘ',
    'how_to_use_app': 'ܐܝܟܢܝܘܬܐ ܕܡܦܠܚܬܐ ܕܐܦܠܝܩܝܫܝܢ',
    'watch_now': 'ܚܙܝ ܗܫܐ',
    'leaderboard_title': 'ܠܘܚܐ ܕܫܘܪܝܐ ܕܨܦܐ',
    'rank': 'ܕܪܓܐ',
    'student_name': 'ܫܡܐ ܕܬܠܡܝܕܐ',
    'average_marks': 'ܡܨܥܝܐ ܕܛܟ̈ܣܐ',
    'select_class': 'ܓܒܝ ܨܦܐ',
    'manage_homework': 'ܢܗܘܓܘܬܐ ܕܥܒܕܐ ܕܒܝܬܐ',
    'submissions': 'ܫܘܠܡ̈ܐ',
    'post_announcement': 'ܫܕܪ ܡܘܕܥܢܘܬܐ',
    'take_attendance': 'ܣܒ ܐܬܘܬܐ',
    'today': 'ܝܘܡܢܐ',
    'update_attendance': 'ܚܕܬ ܐܬܘܬܐ',
    'all_present': 'ܟܠܗܘܢ ܐܝܬܝܗܘܢ',
    'save': 'ܢܛܘܪ',
    'title': 'ܟܘܢܝܐ',
    'description': 'ܦܘܫܩܐ',
    'subject': 'ܡܠܘܐܐ',
    'priority': 'ܩܕܡܝܘܬܐ',
    'content': 'ܡܠܝܘܬܐ',
    'modern_assyrian': 'ܐܬܘܪܝܐ ܚܕܬܐ',
    'kurdish_sorani': 'ܟܘܪܕܝܐ (ܣܘܪܢܝܐ)',
    'kurdish_bahdini': 'ܟܘܪܕܝܐ (ܒܗܕܝܢܢܝܐ)',
    'english': 'ܐܢܓܠܝܐ',
    'arabic': 'ܥܪܒܝܐ',
    'speak': 'ܩܪܝ ܒܩܠܐ',
    'speech_not_supported': 'ܩܪܝܢܐ ܕܟܬܒܐ ܒܩܠܐ ܠܐ ܦܠܚܐ ܒܡܦܐܫܢܐ ܕܐܢܬ.',
    'error_gemini': 'ܠܐ ܡܨܐ ܠܡܩܒܠ ܦܘܣܩܢܐ ܕܐܘܡܢܘܬܐ ܢܟܝܠܬܐ. ܒܒܥܘ ܬܢܝ ܙܒܢܐ ܐܚܪܢܐ.',
    'homework_submission_title': 'ܫܘܠܡ̈ܐ ܕܥܒܕܐ ܕܒܝܬܐ',
    'homework_submission_desc': 'ܠܐ ܓܒܝ ܬܠܡܝ̈ܕܐ ܕܠܐ ܫܠܡܘ ܥܒܕܐ ܕܒܝܬܐ.',
    'select_all': 'ܓܒܝ ܟܠ',
    'deselect_all': 'ܠܐ ܓܒܝ ܟܠ',
    'profile_summary': "ܦܘܣܩܢܐ ܕܦܪܨܘܦܐ ܕ{name}",
    'voice_not_available': "ܩܠܐ ܠܠܫܢܐ {language} ܠܐ ܣܝܡܐ ܥܠ ܓܐܙܐ ܕܐܢܬ.",
    'performance': 'ܦܠܚܐ',
    'admin': 'ܡܕܒܪܢܐ',
    'overview': 'ܚܝܪܐ ܓܘܢܝܐ',
    'teachers': 'ܡܠܦܢ̈ܐ',
    'graded_assignments': 'ܥܒܕ̈ܐ ܕܐܬܛܟܣܘ',
    'total_submissions': 'ܟܠ ܫܘܠܡ̈ܐ',
    'grade_distribution': 'ܦܠܓܘܬܐ ܕܛܟ̈ܣܐ',
    'recent_activity': 'ܓܒܝܬܐ ܚܕܬܐ',
    'search_students': 'ܒܨܝ ܬܠܡܝ̈ܕܐ...',
    'search_teachers': 'ܒܨܝ ܡܠܦܢ̈ܐ...',
    'parent': 'ܐܒܐ',
    'class': 'ܨܦܐ',
    'classes': 'ܨܦ̈ܐ',
    'activity_by_teacher': 'ܓܒܝܬܐ ܒܡܠܦܢܐ',
    'homework_assigned': 'ܥܒܕܐ ܕܒܝܬܐ ܕܐܬܣܝܡ',
    'total_students': 'ܟܠ ܬܠܡܝ̈ܕܐ',
    'total_teachers': 'ܟܠ ܡܠܦܢ̈ܐ',
    'posted_homework': 'ܫܕܪ ܥܒܕܐ ܕܒܝܬܐ',
    'posted_announcement': 'ܫܕܪ ܡܘܕܥܢܘܬܐ',
    'view_stats_for': 'ܚܙܝ ܣܘܟܡ̈ܐ ܠ',
    'school_wide': 'ܚܝܪܐ ܓܘܢܝܐ ܕܡܕܪܫܬܐ',
    'manage_grades': 'ܢܗܘܓܘܬܐ ܕܛܟ̈ܣܐ',
    'create_new_assignment': 'ܒܪܝ ܥܒܕܐ ܚܕܬܐ',
    'edit_grades': 'ܫܚܠܦ ܛܟ̈ܣܐ',
    'assignment_title': 'ܟܘܢܝܐ ܕܥܒܕܐ',
    'max_marks': 'ܛܟ̈ܣܐ ܪבر̈ܒܐ',
    'no_assignments_yet': 'ܠܝܬ ܥܒܕ̈ܐ ܒܪܝ̈ܐ ܠܗܢܐ ܨܦܐ ܥܕܟܝܠ.',
    'save_grades': 'ܢܛܘܪ ܛܟ̈ܣܐ',
    'assignment_details': 'ܦܘ̈ܘܫܩܐ ܕܥܒܕܐ',
    'management': 'ܢܗܘܓܘܬܐ',
    'add_class': 'ܒܪܝ ܨܦܐ',
    'class_name': 'ܫܡܐ ܕܨܦܐ',
    'add_student': 'ܒܪܝ ܬܠܡܝܕܐ',
    'student_name_label': 'ܫܡܐ ܕܬܠܡܝܕܐ',
    'link_to_parent': 'ܩܫܘܪ ܠܐܒܐ',
    'add_teacher': 'ܒܪܝ ܡܠܦܢܐ',
    'teacher_name_label': 'ܫܡܐ ܕܡܠܦܢܐ',
    'assign_to_classes': 'ܣܝܡ ܠܨܦ̈ܐ',
    'add_subject': 'ܒܪܝ ܡܠܘܐܐ',
    'subject_name': 'ܫܡܐ ܕܡܠܘܐܐ',
    'assign_new_homework': 'ܣܝܡ ܥܒܕܐ ܕܒܝܬܐ ܚܕܬܐ',
    'due_date_label': 'ܙܒܢܐ ܕܫܘܠܡܐ',
    'add_parent': 'ܒܪܝ ܐܒܐ',
    'parent_name': 'ܫܡܐ ܕܐܒܐ',
    'class_added': 'ܨܦܐ ܐܬܒܪܝ ܒܢܨܚܢܐ!',
    'student_added': 'ܬܠܡܝܕܐ ܐܬܒܪܝ ܒܢܨܚܢܐ!',
    'subject_added': 'ܡܠܘܐܐ ܐܬܒܪܝ ܒܢܨܚܢܐ!',
    'homework_assigned_success': 'ܥܒܕܐ ܕܒܝܬܐ ܐܬܣܝܡ ܒܢܨܚܢܐ!',
    'announcement_posted_success': 'ܡܘܕܥܢܘܬܐ ܐܬܫܕܪܬ ܒܢܨܚܢܐ!',
    'grades_saved_success': 'ܛܟ̈ܣܐ ܐܬܢܛܪܘ ܒܢܨܚܢܐ!',
    'attendance_saved_success': 'ܐܬܘܬܐ ܐܬܢܛܪܬ ܒܢܨܚܢܐ!',
    'submissions_saved_success': 'ܫܘܠܡ̈ܐ ܐܬܢܛܪܘ ܒܢܨܚܢܐ!',
    'messages': 'ܐܓܪ̈ܬܐ',
    'send_message': 'ܫܕܪ ܐܓܪܬܐ',
    'type_a_message': 'ܟܬܘܒ ܐܓܪܬܐ...',
    'conversation_with': 'ܡܡܠܠܐ ܥܡ {name}',
    'no_messages_yet': 'ܠܝܬ ܐܓܪ̈ܬܐ ܥܕܟܝܠ. ܫܪܝ ܡܡܠܠܐ!',
    'message_sent_success': 'ܐܓܪܬܐ ܐܫܬܕܪܬ ܒܢܨܚܢܐ!',
    'parent_added_with_code': 'ܐܒܐ ܐܬܒܪܝ! ܩܘܕܐ ܕܥܒܪܐ: {code}',
    'teacher_added_with_code': 'ܡܠܦܢܐ ܐܬܒܪܝ! ܩܘܕܐ ܕܥܒܪܐ: {code}',
    'student_added_with_code': 'ܬܠܡܝܕܐ ܐܬܒܪܝ! ܩܘܕܐ ܕܥܒܪܐ: {code}',
    'choose_your_character': 'ܓܒܝ ܢܦܫܟ',
    'hello_student': 'ܫܠܡܐ، {name}!',
    'character_selected': 'ܢܦܫܐ ܓܒܝܐ!',
    'timetable': 'ܙܒܢ̈ܐ ܕܨܦܐ',
    'profile': 'ܦܪܨܘܦܐ',
    'change_photo': 'ܫܚܠܦ ܨܘܪܬܐ',
    'photo_updated_success': 'ܨܘܪܬܐ ܐܬܚܕܬܬ ܒܢܨܚܢܐ!',
    'delete': 'ܫܘܦ',
    'confirm_delete_title': 'ܚܬܡ ܫܘܦܐ',
    'confirm_delete_homework_message': 'ܚܬܡܐܝܬ ܒܥܐ ܐܢܬ ܕܬܫܘܦ ܗܢܐ ܥܒܕܐ ܕܒܝܬܐ؟ ܗܢܐ ܦܘܠܚܢܐ ܠܐ ܡܨܐ ܠܡܗܦܟ.',
    'confirm_delete_assignment_message': 'ܚܬܡܐܝܬ ܒܥܐ ܐܢܬ ܕܬܫܘܦ ܗܢܐ ܥܒܕܐ ܘܟܠܗܘܢ ܛܟ̈ܣܘܗܝ؟ ܗܢܐ ܦܘܠܚܢܐ ܠܐ ܡܨܐ ܠܡܗܦܟ.',
    'cancel': 'ܒܛܘܠ',
    'homework_deleted_success': 'ܥܒܕܐ ܕܒܝܬܐ ܐܫܬܦ ܒܢܨܚܢܐ!',
    'assignment_deleted_success': 'ܥܒܕܐ ܐܫܬܦ ܒܢܨܚܢܐ!',
    'mark_all_present': 'ܟܠܗܘܢ ܚܙܝ',
    'availability': 'ܕܘܙܘܬܐ',
    'available_from': 'ܕܘܙ ܡܢ',
    'available_to': 'ܠ',
    'save_availability': 'ܢܛܘܪ ܕܘܙܘܬܐ',
    'availability_saved_success': 'ܕܘܙܘܬܐ ܐܬܢܛܪܬ ܒܢܨܚܢܐ!',
    'start_recording': 'ܫܪܝ ܩܠܬܐ',
    'stop_recording': 'ܟܠܝ ܩܠܬܐ',
    'send_voice_message': 'ܫܕܪ ܐܓܪܬܐ ܩܠܢܝܬܐ',
    'teacher_available': 'ܕܘܙ: {startTime} - {endTime}',
    'user_codes': 'ܩܘܕ̈ܐ ܕܡܦܠܚܢܐ',
    'filter_by_role': 'ܦܠܛܪ ܒܕܪܓܐ',
    'all_roles': 'ܟܠܗܘܢ ܕܪ̈ܓܐ',
    'parents': 'ܐܒ̈ܗܐ',
    'name': 'ܫܡܐ',
    'role': 'ܕܪܓܐ',
    'code': 'ܩܘܕܐ',
    'actions': 'ܦܘܠܚܢܐ',
    'copy': 'ܢܚܬܐ',
    'loading': 'ܓܒܠ...',
    'student_codes': 'ܩܘܕ̈ܐ ܕܬܠܡܝ̈ܕܐ',
    'student_codes_description': 'ܚܙܝ ܘܢܚܬ ܩܘܕ̈ܐ ܕܥܒܪܐ ܕܐܝܠܢܝܟ',
    'student': 'ܬܠܡܝܕܐ',
    'login_code': 'ܩܘܕܐ ܕܥܒܪܐ',
    'confirm_delete_student': 'ܚܬܡܐܝܬ ܒܥܐ ܐܢܬ ܕܬܫܘܦ ܗܢܐ ܬܠܡܝܕܐ؟',
    'confirm_delete_teacher': 'ܚܬܡܐܝܬ ܒܥܐ ܐܢܬ ܕܬܫܘܦ ܗܢܐ ܡܠܦܢܐ؟',
    'confirm_delete_user': 'ܚܬܡܐܝܬ ܒܥܐ ܐܢܬ ܕܬܫܘܦ {name}؟',
    'no_grades_yet': 'هێشتا هیچ نمرە نەکراوە.',
    'no_teachers_yet': 'هێشتا هیچ مامۆستای نەکراوە.',
    'grades_assigned': 'نمرەکان بە سەرکەوتوویی پاشەکەوت کران.',
    'select_parent': 'دایبابی هەڵبژێرە',
    'no_parents_available': 'هیچ دایبابەکان نەبوو. لەوەی بەردەست بنووسە بە دایبابەکان.',
  }
};